const AmajorChord = {
  none: {},
  barreA: {
    firstString: 0,
    secondString: 2,
    thirdString: 2,
    fourthString: 2,
    fifthString: 0,
    sixthString: -1,
  },
  barreE: {
    firstString: 5,
    secondString: 5,
    thirdString: 6,
    fourthString: 7,
    fifthString: 7,
    sixthString: 5,
  },
  octave: {
    firstString: 12,
    secondString: 14,
    thirdString: 14,
    fourthString: 14,
    fifthString: 12,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 2,
    fourthString: 2,
    fifthString: 0,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 7,
    fifthString: 7,
    sixthString: 5,
  },
};

const AsharpMajorChord = {
  none: {},
  barreA: {
    firstString: 1,
    secondString: 3,
    thirdString: 3,
    fourthString: 3,
    fifthString: 1,
    sixthString: -1,
  },
  barreE: {
    firstString: 6,
    secondString: 6,
    thirdString: 7,
    fourthString: 8,
    fifthString: 8,
    sixthString: 6,
  },
  octave: {
    firstString: 13,
    secondString: 15,
    thirdString: 15,
    fourthString: 15,
    fifthString: 13,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 3,
    fourthString: 3,
    fifthString: 1,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 8,
    fifthString: 8,
    sixthString: 6,
  },
};

const BmajorChord = {
  none: {},
  barreA: {
    firstString: 2,
    secondString: 4,
    thirdString: 4,
    fourthString: 4,
    fifthString: 2,
    sixthString: -1,
  },
  barreE: {
    firstString: 7,
    secondString: 7,
    thirdString: 8,
    fourthString: 9,
    fifthString: 9,
    sixthString: 7,
  },
  octave: {
    firstString: 14,
    secondString: 16,
    thirdString: 16,
    fourthString: 16,
    fifthString: 14,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 4,
    fourthString: 4,
    fifthString: 2,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 9,
    fifthString: 9,
    sixthString: 7,
  },
};

const CmajorChord = {
  none: {},
  open: {
    firstString: 0,
    secondString: 1,
    thirdString: 0,
    fourthString: 2,
    fifthString: 3,
    sixthString: -1,
  },
  barreA: {
    firstString: 3,
    secondString: 5,
    thirdString: 5,
    fourthString: 5,
    fifthString: 3,
    sixthString: -1,
  },
  octave: {
    firstString: 8,
    secondString: 8,
    thirdString: 9,
    fourthString: 10,
    fifthString: 10,
    sixthString: 8,
  },
  power: {
    firstString: -1,
    secondString: -1,
    thirdString: 5,
    fourthString: 5,
    fifthString: 3,
    sixthString: -1,
  },
  power: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 10,
    fifthString: 10,
    sixthString: 8,
  },
};

const CsharpMajorChord = {
  none: {},
  barreA: {
    firstString: 4,
    secondString: 6,
    thirdString: 6,
    fourthString: 6,
    fifthString: 4,
    sixthString: -1,
  },
  barreE: {
    firstString: 9,
    secondString: 9,
    thirdString: 10,
    fourthString: 11,
    fifthString: 11,
    sixthString: 9,
  },
  octave: {
    firstString: 16,
    secondString: 18,
    thirdString: 18,
    fourthString: 18,
    fifthString: 16,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 6,
    fourthString: 6,
    fifthString: 4,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 11,
    fifthString: 11,
    sixthString: 9,
  },
};

const DmajorChord = {
  none: {},
  open: {
    firstString: 2,
    secondString: 3,
    thirdString: 2,
    fourthString: 0,
    fifthString: -1,
    sixthString: -1,
  },
  barreA: {
    firstString: 5,
    secondString: 7,
    thirdString: 7,
    fourthString: 7,
    fifthString: 5,
    sixthString: -1,
  },
  barreE: {
    firstString: 10,
    secondString: 10,
    thirdString: 11,
    fourthString: 12,
    fifthString: 12,
    sixthString: 10,
  },
  octave: {
    firstString: 17,
    secondString: 19,
    thirdString: 19,
    fourthString: 19,
    fifthString: 17,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 7,
    fourthString: 7,
    fifthString: 5,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 12,
    fifthString: 12,
    sixthString: 10,
  },
};

const DsharpMajorChord = {
  none: {},
  barreA: {
    firstString: 6,
    secondString: 8,
    thirdString: 8,
    fourthString: 8,
    fifthString: 6,
    sixthString: -1,
  },
  barreE: {
    firstString: 11,
    secondString: 11,
    thirdString: 12,
    fourthString: 13,
    fifthString: 13,
    sixthString: 11,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 8,
    fourthString: 8,
    fifthString: 6,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 13,
    fifthString: 13,
    sixthString: 11,
  },
};

const EmajorChord = {
  none: {},
  open: {
    firstString: 0,
    secondString: 0,
    thirdString: 1,
    fourthString: 2,
    fifthString: 2,
    sixthString: 0,
  },
  barreA: {
    firstString: 7,
    secondString: 9,
    thirdString: 9,
    fourthString: 9,
    fifthString: 7,
    sixthString: -1,
  },
  barreE: {
    firstString: 12,
    secondString: 12,
    thirdString: 13,
    fourthString: 14,
    fifthString: 14,
    sixthString: 12,
  },
  // octave: {
  //   firstString: 18,
  //   secondString: 20,
  //   thirdString: 20,
  //   fourthString: 20,
  //   fifthString: 18,
  //   sixthString: -1,
  // },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 2,
    fifthString: 2,
    sixthString: 0,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 9,
    fourthString: 9,
    fifthString: 7,
    sixthString: -1,
  },
};

const FmajorChord = {
  none: {},
  barreE: {
    firstString: 1,
    secondString: 1,
    thirdString: 2,
    fourthString: 3,
    fifthString: 3,
    sixthString: 1,
  },
  barreA: {
    firstString: 8,
    secondString: 10,
    thirdString: 10,
    fourthString: 10,
    fifthString: 8,
    sixthString: -1,
  },
  octave: {
    firstString: 13,
    secondString: 13,
    thirdString: 14,
    fourthString: 15,
    fifthString: 15,
    sixthString: 13,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 3,
    fifthString: 3,
    sixthString: 1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 10,
    fourthString: 10,
    fifthString: 8,
    sixthString: -1,
  },
};

const FsharpMajorChord = {
  none: {},
  barreE: {
    firstString: 2,
    secondString: 2,
    thirdString: 3,
    fourthString: 4,
    fifthString: 4,
    sixthString: 2,
  },
  barreA: {
    firstString: 9,
    secondString: 11,
    thirdString: 11,
    fourthString: 11,
    fifthString: 9,
    sixthString: -1,
  },
  octave: {
    firstString: 14,
    secondString: 14,
    thirdString: 15,
    fourthString: 16,
    fifthString: 16,
    sixthString: 14,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 4,
    fifthString: 4,
    sixthString: 2,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 11,
    fourthString: 11,
    fifthString: 9,
    sixthString: -1,
  },
};

const GmajorChord = {
  none: {},
  open: {
    firstString: 3,
    secondString: 3,
    thirdString: 0,
    fourthString: 0,
    fifthString: 2,
    sixthString: 3,
  },
  barreE: {
    firstString: 3,
    secondString: 3,
    thirdString: 4,
    fourthString: 5,
    fifthString: 5,
    sixthString: 3,
  },
  barreA: {
    firstString: 10,
    secondString: 12,
    thirdString: 12,
    fourthString: 12,
    fifthString: 10,
    sixthString: -1,
  },
  octave: {
    firstString: 15,
    secondString: 15,
    thirdString: 16,
    fourthString: 17,
    fifthString: 17,
    sixthString: 15,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 5,
    fifthString: 5,
    sixthString: 3,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 12,
    fourthString: 12,
    fifthString: 10,
    sixthString: -1,
  },
};

const GsharpMajorChord = {
  none: {},
  barreE: {
    firstString: 4,
    secondString: 4,
    thirdString: 5,
    fourthString: 6,
    fifthString: 6,
    sixthString: 4,
  },
  barreA: {
    firstString: 11,
    secondString: 13,
    thirdString: 13,
    fourthString: 13,
    fifthString: 11,
    sixthString: -1,
  },
  octave: {
    firstString: 15,
    secondString: 15,
    thirdString: 15,
    fourthString: 17,
    fifthString: 17,
    sixthString: 15,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 6,
    fifthString: 6,
    sixthString: 4,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 13,
    fourthString: 13,
    fifthString: 11,
    sixthString: -1,
  },
};

const AminorChord = {
  none: {},
  barreA: {
    firstString: 0,
    secondString: 1,
    thirdString: 2,
    fourthString: 2,
    fifthString: 0,
    sixthString: -1,
  },
  barreE: {
    firstString: 5,
    secondString: 5,
    thirdString: 5,
    fourthString: 7,
    fifthString: 7,
    sixthString: 5,
  },
  octave: {
    firstString: 12,
    secondString: 13,
    thirdString: 14,
    fourthString: 14,
    fifthString: 12,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 2,
    fourthString: 2,
    fifthString: 0,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 7,
    fifthString: 7,
    sixthString: 5,
  },
};

const AsharpMinorChord = {
  none: {},
  barreA: {
    firstString: 1,
    secondString: 2,
    thirdString: 3,
    fourthString: 3,
    fifthString: 1,
    sixthString: -1,
  },
  barreE: {
    firstString: 6,
    secondString: 6,
    thirdString: 6,
    fourthString: 8,
    fifthString: 8,
    sixthString: 6,
  },
  octave: {
    firstString: 13,
    secondString: 14,
    thirdString: 15,
    fourthString: 15,
    fifthString: 13,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 3,
    fourthString: 3,
    fifthString: 1,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 8,
    fifthString: 8,
    sixthString: 6,
  },
};

const BminorChord = {
  none: {},
  barreA: {
    firstString: 2,
    secondString: 3,
    thirdString: 4,
    fourthString: 4,
    fifthString: 2,
    sixthString: -1,
  },
  barreE: {
    firstString: 7,
    secondString: 7,
    thirdString: 7,
    fourthString: 9,
    fifthString: 9,
    sixthString: 7,
  },
  octave: {
    firstString: 14,
    secondString: 15,
    thirdString: 16,
    fourthString: 16,
    fifthString: 14,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 4,
    fourthString: 4,
    fifthString: 2,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 9,
    fifthString: 9,
    sixthString: 7,
  },
};

const CminorChord = {
  none: {},
  barreA: {
    firstString: 3,
    secondString: 4,
    thirdString: 5,
    fourthString: 5,
    fifthString: 3,
    sixthString: -1,
  },
  octave: {
    firstString: 8,
    secondString: 8,
    thirdString: 8,
    fourthString: 10,
    fifthString: 10,
    sixthString: 8,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 5,
    fourthString: 5,
    fifthString: 3,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 10,
    fifthString: 10,
    sixthString: 8,
  },
};

const CsharpMinorChord = {
  none: {},
  barreA: {
    firstString: 4,
    secondString: 5,
    thirdString: 6,
    fourthString: 6,
    fifthString: 4,
    sixthString: -1,
  },
  barreE: {
    firstString: 9,
    secondString: 9,
    thirdString: 9,
    fourthString: 11,
    fifthString: 11,
    sixthString: 9,
  },
  octave: {
    firstString: 16,
    secondString: 17,
    thirdString: 18,
    fourthString: 18,
    fifthString: 16,
    sixthString: -1,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 6,
    fourthString: 6,
    fifthString: 4,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 11,
    fifthString: 11,
    sixthString: 9,
  },
};

const DminorChord = {
  none: {},
  open: {
    firstString: 1,
    secondString: 3,
    thirdString: 2,
    fourthString: 0,
    fifthString: -1,
    sixthString: -1,
  },
  barreA: {
    firstString: 5,
    secondString: 6,
    thirdString: 7,
    fourthString: 7,
    fifthString: 5,
    sixthString: -1,
  },
  barreE: {
    firstString: 10,
    secondString: 10,
    thirdString: 10,
    fourthString: 12,
    fifthString: 12,
    sixthString: 10,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 7,
    fourthString: 7,
    fifthString: 5,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 7,
    fourthString: 7,
    fifthString: 5,
    sixthString: -1,
  },
};

const DsharpMinorChord = {
  none: {},
  barreA: {
    firstString: 6,
    secondString: 7,
    thirdString: 8,
    fourthString: 8,
    fifthString: 6,
    sixthString: -1,
  },
  barreE: {
    firstString: 11,
    secondString: 11,
    thirdString: 11,
    fourthString: 13,
    fifthString: 13,
    sixthString: 11,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: 8,
    fourthString: 8,
    fifthString: 6,
    sixthString: -1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 13,
    fifthString: 13,
    sixthString: 11,
  },
};

const EminorChord = {
  none: {},
  open: {
    firstString: 0,
    secondString: 0,
    thirdString: 0,
    fourthString: 2,
    fifthString: 2,
    sixthString: 0,
  },
  barreA: {
    firstString: 7,
    secondString: 8,
    thirdString: 9,
    fourthString: 9,
    fifthString: 7,
    sixthString: -1,
  },
  barreE: {
    firstString: 12,
    secondString: 12,
    thirdString: 12,
    fourthString: 14,
    fifthString: 14,
    sixthString: 12,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 2,
    fifthString: 2,
    sixthString: 0,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 9,
    fourthString: 9,
    fifthString: 7,
    sixthString: -1,
  },
};

const FminorChord = {
  none: {},
  barreE: {
    firstString: 1,
    secondString: 1,
    thirdString: 1,
    fourthString: 3,
    fifthString: 3,
    sixthString: 1,
  },
  barreA: {
    firstString: 8,
    secondString: 9,
    thirdString: 10,
    fourthString: 10,
    fifthString: 8,
    sixthString: -1,
  },
  octave: {
    firstString: 13,
    secondString: 13,
    thirdString: 13,
    fourthString: 15,
    fifthString: 15,
    sixthString: 13,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 3,
    fifthString: 3,
    sixthString: 1,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 10,
    fourthString: 10,
    fifthString: 8,
    sixthString: -1,
  },
};

const FsharpMinorChord = {
  none: {},
  barreE: {
    firstString: 2,
    secondString: 2,
    thirdString: 2,
    fourthString: 4,
    fifthString: 4,
    sixthString: 2,
  },
  barreA: {
    firstString: 9,
    secondString: 10,
    thirdString: 11,
    fourthString: 11,
    fifthString: 9,
    sixthString: -1,
  },
  octave: {
    firstString: 14,
    secondString: 14,
    thirdString: 14,
    fourthString: 16,
    fifthString: 16,
    sixthString: 14,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 4,
    fifthString: 4,
    sixthString: 2,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 11,
    fourthString: 11,
    fifthString: 9,
    sixthString: -1,
  },
};

const GminorChord = {
  none: {},
  barreE: {
    firstString: 3,
    secondString: 3,
    thirdString: 3,
    fourthString: 5,
    fifthString: 5,
    sixthString: 3,
  },
  barreA: {
    firstString: 10,
    secondString: 11,
    thirdString: 12,
    fourthString: 12,
    fifthString: 10,
    sixthString: -1,
  },
  octave: {
    firstString: 14,
    secondString: 14,
    thirdString: 14,
    fourthString: 16,
    fifthString: 16,
    sixthString: 14,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 5,
    fifthString: 5,
    sixthString: 3,
  },
  power: {
    firstString: -1,
    secondString: -1,
    thirdString: 12,
    fourthString: 12,
    fifthString: 10,
    sixthString: -1,
  },
};

const GsharpMinorChord = {
  none: {},
  barreE: {
    firstString: 4,
    secondString: 4,
    thirdString: 4,
    fourthString: 6,
    fifthString: 6,
    sixthString: 4,
  },
  barreA: {
    firstString: 11,
    secondString: 12,
    thirdString: 13,
    fourthString: 13,
    fifthString: 11,
    sixthString: -1,
  },
  octave: {
    firstString: 15,
    secondString: 15,
    thirdString: 15,
    fourthString: 17,
    fifthString: 17,
    sixthString: 15,
  },
  power1: {
    firstString: -1,
    secondString: -1,
    thirdString: -1,
    fourthString: 6,
    fifthString: 6,
    sixthString: 4,
  },
  power2: {
    firstString: -1,
    secondString: -1,
    thirdString: 13,
    fourthString: 13,
    fifthString: 11,
    sixthString: -1,
  },
};

const Adim7flat5 = {
  none: {},
  movable: {
    firstString: -1,
    secondString: 1,
    thirdString: 0,
    fourthString: 1,
    fifthString: 0,
    sixthString: -1,
  },
};
const Bdim7flat5 = {
  none: {},
  movable: {
    firstString: -1,
    secondString: 3,
    thirdString: 2,
    fourthString: 3,
    fifthString: 2,
    sixthString: -1,
  },
};
