const EStandard = {
  name: "EStandard",
  tuning: ["E", "A", "D", "G", "B", "E"],
  strings: {
    firstString: [
      { Note: "E", FretNumber: 0 },
      { Note: "F", FretNumber: 1 },
      { Note: "F#", FretNumber: 2 },
      { Note: "G", FretNumber: 3 },
      { Note: "G#", FretNumber: 4 },
      { Note: "A", FretNumber: 5 },
      { Note: "A#", FretNumber: 6 },
      { Note: "B", FretNumber: 7 },
      { Note: "C", FretNumber: 8 },
      { Note: "C#", FretNumber: 9 },
      { Note: "D", FretNumber: 10 },
      { Note: "D#", FretNumber: 11 },
      { Note: "E", FretNumber: 12 },
      { Note: "F", FretNumber: 13 },
      { Note: "F#", FretNumber: 14 },
      { Note: "G", FretNumber: 15 },
      { Note: "G#", FretNumber: 16 },
      { Note: "A", FretNumber: 17 },
      { Note: "A#", FretNumber: 18 },
      { Note: "B", FretNumber: 19 },
      { Note: "C", FretNumber: 20 },
      { Note: "C#", FretNumber: 21 },
      { Note: "D", FretNumber: 22 },
    ],

    secondString: [
      { Note: "B", FretNumber: 0 },
      { Note: "C", FretNumber: 1 },
      { Note: "C#", FretNumber: 2 },
      { Note: "D", FretNumber: 3 },
      { Note: "D#", FretNumber: 4 },
      { Note: "E", FretNumber: 5 },
      { Note: "F", FretNumber: 6 },
      { Note: "F#", FretNumber: 7 },
      { Note: "G", FretNumber: 8 },
      { Note: "G#", FretNumber: 9 },
      { Note: "A", FretNumber: 10 },
      { Note: "A#", FretNumber: 11 },
      { Note: "B", FretNumber: 12 },
      { Note: "C", FretNumber: 13 },
      { Note: "C#", FretNumber: 14 },
      { Note: "D", FretNumber: 15 },
      { Note: "D#", FretNumber: 16 },
      { Note: "E", FretNumber: 17 },
      { Note: "F", FretNumber: 18 },
      { Note: "F#", FretNumber: 19 },
      { Note: "G", FretNumber: 20 },
      { Note: "G#", FretNumber: 21 },
      { Note: "A", FretNumber: 22 },
    ],

    thirdString: [
      { Note: "G", FretNumber: 0 },
      { Note: "G#", FretNumber: 1 },
      { Note: "A", FretNumber: 2 },
      { Note: "A#", FretNumber: 3 },
      { Note: "B", FretNumber: 4 },
      { Note: "C", FretNumber: 5 },
      { Note: "C#", FretNumber: 6 },
      { Note: "D", FretNumber: 7 },
      { Note: "D#", FretNumber: 8 },
      { Note: "E", FretNumber: 9 },
      { Note: "F", FretNumber: 10 },
      { Note: "F#", FretNumber: 11 },
      { Note: "G", FretNumber: 12 },
      { Note: "G#", FretNumber: 13 },
      { Note: "A", FretNumber: 14 },
      { Note: "A#", FretNumber: 15 },
      { Note: "B", FretNumber: 16 },
      { Note: "C", FretNumber: 17 },
      { Note: "C#", FretNumber: 18 },
      { Note: "D", FretNumber: 19 },
      { Note: "D#", FretNumber: 20 },
      { Note: "E", FretNumber: 21 },
      { Note: "F", FretNumber: 22 },
    ],

    fourthString: [
      { Note: "D", FretNumber: 0 },
      { Note: "D#", FretNumber: 1 },
      { Note: "E", FretNumber: 2 },
      { Note: "F", FretNumber: 3 },
      { Note: "F#", FretNumber: 4 },
      { Note: "G", FretNumber: 5 },
      { Note: "G#", FretNumber: 6 },
      { Note: "A", FretNumber: 7 },
      { Note: "A#", FretNumber: 8 },
      { Note: "B", FretNumber: 9 },
      { Note: "C", FretNumber: 10 },
      { Note: "C#", FretNumber: 11 },
      { Note: "D", FretNumber: 12 },
      { Note: "D#", FretNumber: 13 },
      { Note: "E", FretNumber: 14 },
      { Note: "F", FretNumber: 15 },
      { Note: "F#", FretNumber: 16 },
      { Note: "G", FretNumber: 17 },
      { Note: "G#", FretNumber: 18 },
      { Note: "A", FretNumber: 19 },
      { Note: "A#", FretNumber: 20 },
      { Note: "B", FretNumber: 21 },
      { Note: "C", FretNumber: 22 },
    ],

    fifthString: [
      { Note: "A", FretNumber: 0 },
      { Note: "A#", FretNumber: 1 },
      { Note: "B", FretNumber: 2 },
      { Note: "C", FretNumber: 3 },
      { Note: "C#", FretNumber: 4 },
      { Note: "D", FretNumber: 5 },
      { Note: "D#", FretNumber: 6 },
      { Note: "E", FretNumber: 7 },
      { Note: "F", FretNumber: 8 },
      { Note: "F#", FretNumber: 9 },
      { Note: "G", FretNumber: 10 },
      { Note: "G#", FretNumber: 11 },
      { Note: "A", FretNumber: 12 },
      { Note: "A#", FretNumber: 13 },
      { Note: "B", FretNumber: 14 },
      { Note: "C", FretNumber: 15 },
      { Note: "C#", FretNumber: 16 },
      { Note: "D", FretNumber: 17 },
      { Note: "D#", FretNumber: 18 },
      { Note: "E", FretNumber: 19 },
      { Note: "F", FretNumber: 20 },
      { Note: "F#", FretNumber: 21 },
      { Note: "G", FretNumber: 22 },
    ],

    sixthString: [
      { Note: "E", FretNumber: 0 },
      { Note: "F", FretNumber: 1 },
      { Note: "F#", FretNumber: 2 },
      { Note: "G", FretNumber: 3 },
      { Note: "G#", FretNumber: 4 },
      { Note: "A", FretNumber: 5 },
      { Note: "A#", FretNumber: 6 },
      { Note: "B", FretNumber: 7 },
      { Note: "C", FretNumber: 8 },
      { Note: "C#", FretNumber: 9 },
      { Note: "D", FretNumber: 10 },
      { Note: "D#", FretNumber: 11 },
      { Note: "E", FretNumber: 12 },
      { Note: "F", FretNumber: 13 },
      { Note: "F#", FretNumber: 14 },
      { Note: "G", FretNumber: 15 },
      { Note: "G#", FretNumber: 16 },
      { Note: "A", FretNumber: 17 },
      { Note: "A#", FretNumber: 18 },
      { Note: "B", FretNumber: 19 },
      { Note: "C", FretNumber: 20 },
      { Note: "C#", FretNumber: 21 },
      { Note: "D", FretNumber: 22 },
    ],
  },
};
